//
//  Currencies.swift
//  CurrencyConverter
//
//  Created by Tim Neal on 7/30/21.
//  Copyright © 2021 Tim Neal. All rights reserved.
//

class Currencies {
    var currencyObjects = [
        Currency(currencyCode: "AED", currencyName: "United Arab Emirates Dirham", countryName: "United Arab Emirates"),
        Currency(currencyCode: "AFN", currencyName: "Afghan Afghani", countryName: "Afghanistan"),
        Currency(currencyCode: "ALL", currencyName: "Albanian Lek", countryName: "Albania"),
        Currency(currencyCode: "AMD", currencyName: "Armenian Dram", countryName: "Armenia"),
        Currency(currencyCode: "ANG", currencyName: "Netherlands Antillean Guilder", countryName: "Curacao"),
        Currency(currencyCode: "AOA", currencyName: "Angolan Kwanza", countryName: "Angola"),
        Currency(currencyCode: "ARS", currencyName: "Argentine Peso", countryName: "Argentina"),
        Currency(currencyCode: "AUD", currencyName: "Australian Dollar", countryName: "Australia"),
        Currency(currencyCode: "AWG", currencyName: "Aruban Florin", countryName: "Aruba"),
        Currency(currencyCode: "AZN", currencyName: "Azerbaijani Manat", countryName: "Azerbaijan"),
        Currency(currencyCode: "BAM", currencyName: "Convertible Mark", countryName: "Bosnia and Herzegovina"),
        Currency(currencyCode: "BBD", currencyName: "Barbadian Dollar", countryName: "Barbados"),
        Currency(currencyCode: "BDT", currencyName: "Bangladeshi Taka", countryName: "Bangladesh"),
        Currency(currencyCode: "BGN", currencyName: "Bulgarian Lev", countryName: "Bulgaria"),
        Currency(currencyCode: "BHD", currencyName: "Bahraini Dinar", countryName: "Bahrain"),
        Currency(currencyCode: "BIF", currencyName: "Burundian Franc", countryName: "Burundi"),
        Currency(currencyCode: "BMD", currencyName: "Bermudian Dollar", countryName: "Bermuda"),
        Currency(currencyCode: "BND", currencyName: "Brunei Dollar", countryName: "Brunei"),
        Currency(currencyCode: "BOB", currencyName: "Bolivian Boliviano", countryName: "Bolivia"),
        Currency(currencyCode: "BRL", currencyName: "Brazilian Real", countryName: "Brazil"),
        Currency(currencyCode: "BSD", currencyName: "Bahamian Dollar", countryName: "Bahamas"),
        Currency(currencyCode: "BTN", currencyName: "Bhutanese Ngultrum", countryName: "Bhutan"),
        Currency(currencyCode: "BWP", currencyName: "Botswanan Pula", countryName: "Botswana"),
        Currency(currencyCode: "BYN", currencyName: "Belarusian Ruble", countryName: "Belarus"),
        Currency(currencyCode: "BZD", currencyName: "Belize Dollar", countryName: "Belize"),
        Currency(currencyCode: "CAD", currencyName: "Canadian Dollar", countryName: "Canada"),
        Currency(currencyCode: "CDF", currencyName: "Congolese Franc", countryName: "Democratic Republic of the Congo"),
        Currency(currencyCode: "CHF", currencyName: "Swiss Franc", countryName: "Switzerland"),
        Currency(currencyCode: "CLP", currencyName: "Chilean Peso", countryName: "Chile"),
        Currency(currencyCode: "CNY", currencyName: "Chinese Yuan Renminbi", countryName: "China"),
        Currency(currencyCode: "COP", currencyName: "Colombian Peso", countryName: "Colombia"),
        Currency(currencyCode: "CRC", currencyName: "Costa Rican Colon", countryName: "Costa Rica"),
        Currency(currencyCode: "CUP", currencyName: "Cuban Peso", countryName: "Cuba"),
        Currency(currencyCode: "CVE", currencyName: "Cape Verdean Escudo", countryName: "Republic of Cape Verde"),
        Currency(currencyCode: "CZK", currencyName: "Czech Koruna", countryName: "Czech Republic"),
        Currency(currencyCode: "DJF", currencyName: "Djiboutian Franc", countryName: "Djibouti"),
        Currency(currencyCode: "DKK", currencyName: "Danish Krone", countryName: "Denmark, Greenland, Faroe Islands"),
        Currency(currencyCode: "DOP", currencyName: "Dominican Peso", countryName: "Dominican Republic"),
        Currency(currencyCode: "DZD", currencyName: "Algerian Dinar", countryName: "Algeria"),
        Currency(currencyCode: "EGP", currencyName: "Egyptian Pound", countryName: "Egypt"),
        Currency(currencyCode: "ERN", currencyName: "Eritrean Nakfa", countryName: "Eritrea"),
        Currency(currencyCode: "ETB", currencyName: "Ethiopian Birr", countryName: "Ethiopia"),
        Currency(currencyCode: "EUR", currencyName: "Euro", countryName: "European Union"),
        Currency(currencyCode: "FJD", currencyName: "Fijian Dollar", countryName: "Fiji"),
        Currency(currencyCode: "FKP", currencyName: "Falkland Islands Pound", countryName: "Falkland Islands"),
        Currency(currencyCode: "GBP", currencyName: "Pound Sterling", countryName: "Great Britian"),
        Currency(currencyCode: "GEL", currencyName: "Georgian Lari", countryName: "Georgia"),
        Currency(currencyCode: "GGP", currencyName: "Guernsey Pound", countryName: "Guernsey"),
        Currency(currencyCode: "GHS", currencyName: "Ghanaian Cedi", countryName: "Ghana"),
        Currency(currencyCode: "GIP", currencyName: "Gibraltar Pound", countryName: "Gibraltar"),
        Currency(currencyCode: "GMD", currencyName: "Gambian Dalasi", countryName: "Gambia"),
        Currency(currencyCode: "GNF", currencyName: "Guinean Franc", countryName: "Guinea"),
        Currency(currencyCode: "GTQ", currencyName: "Guatemalan Quetzal", countryName: "Guatemala"),
        Currency(currencyCode: "HKD", currencyName: "Hong Kong Dollar", countryName: "Hong Kong"),
        Currency(currencyCode: "HNL", currencyName: "Honduran Lempira", countryName: "Honduras"),
        Currency(currencyCode: "HRK", currencyName: "Croatian Kuna", countryName: "Croatia"),
        Currency(currencyCode: "HTG", currencyName: "Haitian Gourde", countryName: "Haiti"),
        Currency(currencyCode: "HUF", currencyName: "Forint", countryName: "Hungary"),
        Currency(currencyCode: "IDR", currencyName: "Indonesian Rupiah", countryName: "Indonesia"),
        Currency(currencyCode: "ILS", currencyName: "Israeli New Shekel", countryName: "Isreal"),
        Currency(currencyCode: "INR", currencyName: "Indian Rupee", countryName: "India"),
        Currency(currencyCode: "IQD", currencyName: "Iraqi Dinar", countryName: "Iraq"),
        Currency(currencyCode: "IRR", currencyName: "Iranian Rial", countryName: "Iran"),
        Currency(currencyCode: "ISK", currencyName: "Icelandic Krona", countryName: "Iceland"),
        Currency(currencyCode: "JEP", currencyName: "Jersey Pound", countryName: "Jersey"),
        Currency(currencyCode: "JMD", currencyName: "Jamaican Dollar", countryName: "Jamaica"),
        Currency(currencyCode: "JOD", currencyName: "Jordanian Dinar", countryName: "Jordan"),
        Currency(currencyCode: "JPY", currencyName: "Japanese Yen", countryName: "Japan"),
        Currency(currencyCode: "KES", currencyName: "Kenyan Shilling", countryName: "Kenya"),
        Currency(currencyCode: "KGS", currencyName: "Kyrgystani Som", countryName: "Kyrgyz Republic"),
        Currency(currencyCode: "KHR", currencyName: "Cambodian Riel", countryName: "Cambodia"),
        Currency(currencyCode: "KMF", currencyName: "Comorian Franc", countryName: "Comoros"),
        Currency(currencyCode: "KPW", currencyName: "North Korean Won", countryName: "North Korea"),
        Currency(currencyCode: "KRW", currencyName: "South Korean Won", countryName: "South Korea"),
        Currency(currencyCode: "KWD", currencyName: "Kuwaiti Dinar", countryName: "Kuwait"),
        Currency(currencyCode: "KYD", currencyName: "Cayman Islands Dollar", countryName: "Cayman Islands"),
        Currency(currencyCode: "KZT", currencyName: "Kazakhstani Tenge", countryName: "Kazakhstan"),
        Currency(currencyCode: "LAK", currencyName: "Laotian Kip", countryName: "Laos"),
        Currency(currencyCode: "LBP", currencyName: "Lebanese Pound", countryName: "Lebanon"),
        Currency(currencyCode: "LKR", currencyName: "Sri Lankan Rupee", countryName: "Sri Lanka"),
        Currency(currencyCode: "LRD", currencyName: "Liberian Dollar", countryName: "Liberia"),
        Currency(currencyCode: "LSL", currencyName: "Lesotho Loti", countryName: "Kingdom of Lesotho"),
        Currency(currencyCode: "LYD", currencyName: "Libyan Dinar", countryName: "Libya"),
        Currency(currencyCode: "MAD", currencyName: "Moroccan Dirham", countryName: "Morocco"),
        Currency(currencyCode: "MDL", currencyName: "Moldovan Leu", countryName: "Moldova"),
        Currency(currencyCode: "MGA", currencyName: "Malagasy Ariary", countryName: "Madagascar"),
        Currency(currencyCode: "MKD", currencyName: "Macedonian Denar", countryName: "North Macedonia"),
        Currency(currencyCode: "MMK", currencyName: "Myanmar Kyat", countryName: "Myanmar"),
        Currency(currencyCode: "MNT", currencyName: "Mongolian Togrog", countryName: "Mongolia"),
        Currency(currencyCode: "MRU", currencyName: "Mauritanian Ouguiya", countryName: "Mauritania"),
        Currency(currencyCode: "MUR", currencyName: "Mauritian Rupee", countryName: "Mauritius"),
        Currency(currencyCode: "MVR", currencyName: "Maldivian Rufiyaa", countryName: "Maldives"),
        Currency(currencyCode: "MWK", currencyName: "Malawian Kwacha", countryName: "Malawi"),
        Currency(currencyCode: "MXN", currencyName: "Mexican Peso", countryName: "Mexico"),
        Currency(currencyCode: "MYR", currencyName: "Malaysian Ringgit", countryName: "Malaysia"),
        Currency(currencyCode: "MZN", currencyName: "Mozambican Metical", countryName: "Mozambique"),
        Currency(currencyCode: "NAD", currencyName: "Namibian Dollar", countryName: "Namibia"),
        Currency(currencyCode: "NGN", currencyName: "Nigerian Naira", countryName: "Nigeria"),
        Currency(currencyCode: "NIO", currencyName: "Nicaraguan Cordoba", countryName: "Nicaragua"),
        Currency(currencyCode: "NOK", currencyName: "Norwegian Krone", countryName: "Norway"),
        Currency(currencyCode: "NPR", currencyName: "Nepalese Rupee", countryName: "Nepal"),
        Currency(currencyCode: "NZD", currencyName: "New Zealand Dollar", countryName: "New Zealand"),
        Currency(currencyCode: "OMR", currencyName: "Omani Rial", countryName: "Oman"),
        Currency(currencyCode: "PAB", currencyName: "Panamanian Balboa", countryName: "Panama"),
        Currency(currencyCode: "PEN", currencyName: "Peruvian Sol", countryName: "Peru"),
        Currency(currencyCode: "PGK", currencyName: "Papua New Guinea", countryName: "Papua New Guinean Kina"),
        Currency(currencyCode: "PHP", currencyName: "Philippine Peso", countryName: "Philippines"),
        Currency(currencyCode: "PKR", currencyName: "Pakistani Rupee", countryName: "Pakistan"),
        Currency(currencyCode: "PLN", currencyName: "Zloty", countryName: "Poland"),
        Currency(currencyCode: "PYG", currencyName: "Paraguayan Guarani", countryName: "Paraguay"),
        Currency(currencyCode: "QAR", currencyName: "Qatari Riyal", countryName: "Qatar"),
        Currency(currencyCode: "RON", currencyName: "Romanian Leu", countryName: "Romania"),
        Currency(currencyCode: "RSD", currencyName: "Serbian Dinar", countryName: "Serbia"),
        Currency(currencyCode: "RUB", currencyName: "Russian Ruble", countryName: "Russia"),
        Currency(currencyCode: "RWF", currencyName: "Rwandan Franc", countryName: "Rwanda"),
        Currency(currencyCode: "SAR", currencyName: "Saudi Riyal", countryName: "Saudi Arabia"),
        Currency(currencyCode: "SBD", currencyName: "Solomon Islands Dollar", countryName: "Solomon Islands"),
        Currency(currencyCode: "SCR", currencyName: "Seychellois Rupee", countryName: "Seychelles"),
        Currency(currencyCode: "SDG", currencyName: "Sudanese Pound", countryName: "Republic of the Sudan"),
        Currency(currencyCode: "SEK", currencyName: "Swedish Krona", countryName: "Sweden"),
        Currency(currencyCode: "SGD", currencyName: "Singapore Dollar", countryName: "Singapore"),
        Currency(currencyCode: "SLL", currencyName: "Sierra Leonean Leone", countryName: "Sierra Leone"),
        Currency(currencyCode: "SOS", currencyName: "Somali Shilling", countryName: "Somalia"),
        Currency(currencyCode: "SRD", currencyName: "Surinamese Dollar", countryName: "Suriname"),
        Currency(currencyCode: "SSP", currencyName: "South Sudanese Pound", countryName: "Republic of South Sudan"),
        Currency(currencyCode: "STN", currencyName: "Sao Tomean Dobra", countryName: "Sao Tome and Principe"),
        Currency(currencyCode: "SVC", currencyName: "Salvadoran Colon", countryName: "El Salvador"),
        Currency(currencyCode: "SYP", currencyName: "Syrian Pound", countryName: "Syria"),
        Currency(currencyCode: "SZL", currencyName: "Swazi Lilangeni", countryName: "Eswatini"),
        Currency(currencyCode: "THB", currencyName: "Thai Baht", countryName: "Thailand"),
        Currency(currencyCode: "TJS", currencyName: "Tajikistani Somoni", countryName: "Tajikistan"),
        Currency(currencyCode: "TMT", currencyName: "Turkmenistani Manat", countryName: "Turkmenistan"),
        Currency(currencyCode: "TND", currencyName: "Tunisian Dinar", countryName: "Tunisia"),
        Currency(currencyCode: "TOP", currencyName: "Tongan paʻanga", countryName: "Tonga"),
        Currency(currencyCode: "TRY", currencyName: "Turkish Lira", countryName: "Turkey"),
        Currency(currencyCode: "TTD", currencyName: "Trinidad and Tobago Dollar", countryName: "Trinidad and Tobago"),
        Currency(currencyCode: "TWD", currencyName: "New Taiwan Dollar", countryName: "Taiwan"),
        Currency(currencyCode: "UAH", currencyName: "Ukrainian Hryvnia", countryName: "Ukraine"),
        Currency(currencyCode: "UGX", currencyName: "Ugandan Shilling", countryName: "Uganda"),
        Currency(currencyCode: "USD", currencyName: "United States Dollar", countryName: "United States of America"),
        Currency(currencyCode: "UYU", currencyName: "Uruguayan Peso", countryName: "Uruguay"),
        Currency(currencyCode: "UZS", currencyName: "Uzbekistan Som", countryName: "Uzbekistan"),
        Currency(currencyCode: "VES", currencyName: "Bolívar Soberano", countryName: "Venezuela"),
        Currency(currencyCode: "VND", currencyName: "Vietnamese Dong", countryName: "Vietnam"),
        Currency(currencyCode: "VUV", currencyName: "Vanuatu Vatu", countryName: "Vanuatu"),
        Currency(currencyCode: "WST", currencyName: "Samoan Tala", countryName: "Samoa"),
        Currency(currencyCode: "XCD", currencyName: "Eastern Caribbean Dollar", countryName: "Antigua and Barbuda, and more"),
        Currency(currencyCode: "XOF", currencyName: "West African CFA franc", countryName: "Ivory Coast, Mali, Niger, and more"),
        Currency(currencyCode: "XPF", currencyName: "Central Pacific Franc", countryName: "French Polynesia, New Caledonia"),
        Currency(currencyCode: "YER", currencyName: "Yemeni Rial", countryName: "Yemen"),
        Currency(currencyCode: "ZAR", currencyName: "Rand", countryName: "South Africa"),
        Currency(currencyCode: "ZMW", currencyName: "Zambian kwacha", countryName: "Zambia"),
        Currency(currencyCode: "ZWL", currencyName: "Zimbabwean Dollar", countryName: "Zimbabwe")
    ]
}
